# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
  math_engine:    mathjax
  syntax_highlighter: rouge
highlighter:      rouge

# Build 
exclude:          ["node_modules", "package.json", "gulpfile.js", "README.md", "LICENSE.md"]
future:           true

# Permalinks
permalink:        pretty # /posts/:title
# relative_permalinks: true

# Setup
title:            Kwritin
tagline:          "A coder's blog"
description:      "Good Good Study, Day Day Up."
url:              https://toien.github.io
author:
  name:           'toien.L'
  url:            https://github.com/toien


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      lang:  zh_CN
      image: /public/img/left-bg-3.webp
      excerpt_separator: <!-- more -->

paginate:         6
plugins:          
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
version:          0.0.1
env:              production # develop  

github:           
  repo:           https://github.com/toien/toien.github.io

webmaster_verifications:
  indexnow: d59196332a36421787c92b4abcc964b8
  bing: E9C017B7E5A7E5C8543C9B1CD04F0F82
  # google: 1234
  # alexa: 1234
  # yandex: 1234
  # baidu: 1234
