# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
  math_engine:    mathjax
  syntax_highlighter: rouge
highlighter:      rouge

# Build 
exclude:          ["node_modules", "package.json", "gulpfile.js", "README.md", "LICENSE.md"]
future:           true

# Permalinks
permalink:        pretty # /posts/:title
# relative_permalinks: true

# Setup
title:            Kwritin
tagline:          "A coder's blog"
description:      "Good Good Study, Day Day Up."
url:              https://toien.github.io
# baseurl:          /
author:
  name:           'toien.L'
  url:            https://github.com/toien

paginate:         6
plugins:          
  - 'jekyll-paginate'
  - 'jekyll-sitemap'

# Custom vars
version:          0.0.1
env:              production # develop  

github:           
  repo:           https://github.com/toien/toien.github.io
