# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: toien's blog
email: lshuhuan@yeah.net
description: > # this means to ignore newlines until "baseurl:"
  under constructing...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://toien.github.io" # the base hostname & protocol for your site
permalink: /posts/:title
# twitter_username: jekyllrb
github_username:  toien

# Build settings
markdown: kramdown
