# Dependencies
markdown:         kramdown
kramdown:
  input:          GFM
highlighter:      rouge # 

# Build 
exclude:          ["node_modules", "package.json", "gulpfile.js", "README.md", "LICENSE.md"]
future:           true

# Permalinks
permalink:        pretty # /posts/:title
# relative_permalinks: true

# Setup
title:            Kwritin
tagline:          'A coder blog'
description:      'Good good study, day day up.'
url:              https://toien.github.io
# baseurl:          /
author:
  name:           'toien.L'
  url:            https://github.com/toien

paginate:         6
plugins:          ['jekyll-paginate', 'jekyll-gist']

# Custom vars
version:          0.0.1
env:              production # develop  

github:           
  repo:           https://github.com/toien/toien.github.io
